### ISSUE TITLE
Optimization and Code-gen wishlist/checklist [help-wanted]

### ISSUE THREAD

**Issue by Hendiadyoin1** [seven1m/natalie#431]
This mostly concerns what is currently Pass0c, Pass1 and Pass4.

### Architectural:
* [ ] Separate into multiple individually toggleable/debuggeable optimization passes
  This would allow us to enable more of these by default, even in a more compatible mode of operation
* [ ] Move Variable allocation up
  The ast-generator already knows which variables exist, maybe we can jinx it into passing that information along
  This could be a synthetic nil-initialization at the top of a block, or could be done through a scopes meta-data
  The latter could even be used to be a bit more active in the GC process
* [ ] Variable type annotations/guesses
  This could allow us to resolve/devirtualize some calls/sends at compile time
* [ ] Pure boolean or/and/if
* [ ] Flattened `or` and `and` Sexps
  These don't need to be that 'deep'

### Code-generation
* [ ] No single use intermediates
  These are all over the generated code and make it harder to read,
  This would also allow us to make case-statements more linear using proper else-if's
* [ ] Inlining of small functions
* [ ] Typed case-statements
  If all checked cases of a switch statement have the same type we can just check for that type before hand.
  After that we could use actual c++-switch-statements for some of the types:
  * [ ] Integers 
  * [ ] Symbols
    These would need to be hashed at compile time
 
### Passes:
* [ ] Constant Propagation
* [ ] Redundant Check Elimination
* [ ] Dead Store Elimination
* [ ] Unused Variable Elimination
* [ ] Unused Function Elimination (affected by inlining)
* [ ] Loop Independent Variable Hoisting

**Comment by seven1m** [comment]
This is quite a large chunk of work, and I can't say I understand all of it.

Of the ones I do understand, I wanted to comment:

>Move Variable allocation up

Why? What's the benefit?

>Pure boolean or/and/if

I assume this means instead of `if (some_value->is_truthy())` you want `if (some_bool)`, but I don't know how you can do that given how dynamic of a language Ruby is.

>Flattened or and and Sexps

I would need to see some performance benefit for this before agreeing we need it.

>No single use intermediates

I'm not against this, but I want to point out the generated C++ is not for a human to read, but for GCC/Clang. If removing the intermediate variables makes our compiler harder to work on or harder to understand, I'm not for it.

>Dead Store Elimination
>Unused Variable Elimination

GCC/Clang does these for us.

>Loop Independent Variable Hoisting

Again, would need to see real-world performance benefit. 

----

I know we have a lot of room for improving the compiler. But we will need to talk through these various things before doing a bunch of work on them -- I just don't want anyone assuming that [my favorite optimization] will be implemented without first discussing the cost/benefit.

I'm going to close this issue. The GitHub issues are a place to list bugs, specs-to-be-implemented, and very specific feature requests. If there's a particular optimization you want to discuss, let's discuss in Discord, or open a targeted GitHub issue for that particular optimization.
